//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Buffstop Xcode Templates
//

import UIKit

protocol ___FILEBASENAMEASIDENTIFIER___DataTransferInterfaceInteractor:class {
    //define Interactors input interface here.
}

class ___FILEBASENAMEASIDENTIFIER___Interactor: ___FILEBASENAMEASIDENTIFIER___DataTransferInterfaceInteractor, ___FILEBASENAMEASIDENTIFIER___RouterDataSource, ___FILEBASENAMEASIDENTIFIER___RouterDataDestination {
    
    var output: ___FILEBASENAMEASIDENTIFIER___DataTransferInterfacePresenter!
    
    // MARK: Business logic

}
