//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift Buff Xcode Templates
//

import Foundation

struct ___FILEBASENAMEASIDENTIFIER___: Equatable
{
    var <#variableName#>: <#Type#>?
    // ...
}

func ==(lhs: ___FILEBASENAMEASIDENTIFIER___, rhs: ___FILEBASENAMEASIDENTIFIER___) -> Bool
{
    return lhs.<#variableName#> == rhs.<#variableName#>
    //&& lhs.<#variableName#> == rhs.<#variableName#> ...
}
