//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Buffstop Xcode Templates
//

import UIKit



struct ___FILEBASENAMEASIDENTIFIER___Scene {
    
    /* Example Model from code snippet
    struct ___FILEBASENAMEASIDENTIFIER___
    {
        struct <#Use Case#> {
            
            struct Request {
                
            }
            
            struct Response {
                
            }
            
            struct ViewModel {
                
            }
        }
    }
 */
    
}
