//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Buffstop Xcode Templates
//

import UIKit



struct ___FILEBASENAMEASIDENTIFIER___Scene {

        /* Example Model
        struct <#Use Case#> {
            
            struct Request {
                
            }
            
            struct Response {
                
            }
            
            struct ViewModel
            {
                struct Displayed<#MyModel#>
                {
                //var id: String
                //var date: String
                // ...
                }
                var displayed<#MyModel#>s: [Displayed<#MyModel#>]
            }
        }
        */
}
