//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Buffstop Xcode Templates
//

import UIKit

protocol ___FILEBASENAMEASIDENTIFIER___DataTransferInterfacePresenter:class {
    //define Presenters input interface here
}

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___DataTransferInterfacePresenter {
    
    weak var output: ___FILEBASENAMEASIDENTIFIER___DataTransferInterfaceView!
    
    // MARK: Presentation logic
    
}
